ubda/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .models import *
from . import db
import time
from datetime import datetime
from werkzeug.security import generate_password_hash
from .device_server import send_reset_cmd

views = Blueprint('views', __name__)


@views.route('/')
@login_required
def home():
    return render_template("home.html", user=current_user)




# @views.route('/add_person', methods=['GET', 'POST'])
# @login_required
# def add_person():
#     if request.method == 'POST':
#         first_name = request.form.get('firstName')
#         last_name = request.form.get('lastName')
#         pin = request.form.get('pin')
#         email = request.form.get('email')
#         access_level = request.form.get('access_level')
#         card_number = request.form.get('card_number')
#         valid_thru = datetime.strptime(request.form.get('valid_thru'), '%Y-%m-%d')
#         person = Person.query.filter_by(pin=pin).first()
#         if person:
#             flash('Pin already exists.', category='error')
#         elif len(pin) < 4:
#             flash('Too short pin', category='error')
#         elif len(first_name) < 1:
#             flash('Too short first name', category='error')
#         else:
#             new_person = Person(first_name=first_name, 
#                                     last_name = last_name, 
#                                     email = email,
#                                     pin = pin,
#                                     card_number = card_number,
#                                     access_level = access_level,
#                                     created_by = current_user.id,
#                                     valid_thru = valid_thru)
#             db.session.add(new_person)
#             db.session.commit()
#             flash('Person added!', category='success') 
#             #return redirect(url_for('views.personnel')) 
#     accessLevels = Access_level.query.all()
#     return render_template("add_person.html", user=current_user, access_levels = accessLevels)


# @views.route('/delete_person/<string:id>', methods=['GET', 'POST'])
# @login_required
# def delete_person(id):
#     person = Person.query.filter_by(id=id).first()
#     if not person :
#         flash(f'No person with id:{id}', category='error')
#         return redirect(url_for('views.personnel'))

#     if request.method == 'POST':
#         db.session.delete(person)
#         db.session.commit()
#         flash('Person deleted', category='success')
#         return redirect(url_for('views.personnel'))
#     return render_template("delete_person.html", user = current_user, person=person)
    

@views.route('/devices')
@login_required
def devices():
    devs = Device.query.all()
    now = int(time.time()) 
    return render_template("devices.html", user = current_user, devs = devs, now = now)


@views.route('/edit_device/<string:id>', methods=['GET', 'POST'])
@login_required
def edit_device(id):
    device = Device.query.filter_by(id=id).first()
    if not device :
        flash(f'No device with id:{id}', category='error')
        return redirect(url_for('views.devices'))
    if request.method == 'POST':
        name = request.form.get('Name')
        device.name = name
        db.session.add(device)
        db.session.commit()
        flash('Device updated', category='success')
        return redirect(url_for('views.devices'))
    return render_template("edit_device.html", user = current_user, device = device)


@views.route('/delete_device/<string:id>', methods=['GET', 'POST'])
@login_required
def delete_device(id):
    device = Device.query.filter_by(id=id).first()
    if not device :
        flash(f'No device with id:{id}', category='error')
        return redirect(url_for('views.devices'))
    if request.method == 'POST':
        db.session.delete(device)
        db.session.commit()
        flash('Device deleted', category='success')
        return redirect(url_for('views.devices'))
    return render_template("delete_device.html", user = current_user, device=device)

@views.route('/reset_device/<string:id>', methods=['GET', 'POST'])
@login_required
def reset_device(id):
    device = Device.query.filter_by(id=id).first()
    if not device :
        flash(f'No device with id:{id}', category='error')
        return redirect(url_for('views.devices'))
    if request.method == 'POST':
        ###send reset command
        send_reset_cmd(device)
        ###
        flash('Reset request sent', category='success')
        return redirect(url_for('views.devices'))
    return render_template("reset_device.html", user = current_user, device=device)


@views.route('/device_log/<string:id>')
@login_required
def device_log(id):
    device = Device.query.filter_by(id=id).first()
    if not device:
        flash(f'No device with id:{id}', category='error')
        return redirect(url_for('views.devices'))
    else:
        users = User.query.all()
        user_names = {}
        for user in users:
            user_names.update({user.id : f'{user.user_name}({user.first_name} {user.last_name})'})
        return render_template("device_log.html", 
                                user = current_user, 
                                user_names = user_names,
                                device= device)


@views.route('/access_levels')
@login_required
def access_levels():
    accessLevels = Access_level.query.all() 
    return render_template("access_levels.html", user = current_user, access_levels = accessLevels)


@views.route('/add_access_level', methods=['GET', 'POST'])
@login_required
def add_access_level():
    devices = Device.query.all()
    outputs = Output.query.all()
    if request.method == 'POST':
        description = request.form.get('description')
        name = request.form.get('name')    
        access_level = Access_level.query.filter_by(name=name).first()
        if access_level:
            flash(f'Access level with name:"{name}" already exists', category='error')
        elif len(name) < 2:
            flash('Too short name', category='error')
        else:
            new_access_level = Access_level(description = description, name = name)
            for device in devices:
                if request.form.get(device.mac):
                    print(f'd-{device.id}')
                    new_access_level.devices.append(device)
            for output in outputs:
                if request.form.get(str(output.id)):
                    print(f'o-{output.id}')
                    new_access_level.outputs.append(output)
            db.session.add(new_access_level)
            db.session.commit()
            flash('Access level added!', category='success') 
            #return redirect(url_for('views.access_levels'))     
    return render_template("add_access_level.html", user = current_user, 
                                                    devices = devices, 
                                                    outputs = outputs)


@views.route('/edit_access_level/<string:id>', methods=['GET', 'POST'])
@login_required
def edit_access_level(id):
    access_level = Access_level.query.filter_by(id=id).first()
    devices = Device.query.all()
    if not access_level :
        flash(f'No Access level with id:{id}', category='error')
        return redirect(url_for('views.access_levels'))  
    if request.method == 'POST':
        outputs = Output.query.all()
        access_level.description = request.form.get('description')
        access_level.name = request.form.get('name')
        for device in devices:
            if request.form.get(device.mac):
                access_level.devices.append(device)
        for output in outputs:
            if request.form.get(str(output.id)):
                access_level.outputs.append(output)
        db.session.add(access_level)
        db.session.commit()
        flash('Access level updated', category='success')
        return redirect(url_for('views.access_levels'))
    return render_template("edit_access_level.html", user = current_user, 
                                                    access_level = access_level, 
                                                    devices=devices)


@views.route('/delete_access_level/<string:id>', methods=['GET', 'POST'])
@login_required
def delete_access_level(id):
    access_level = Access_level.query.filter_by(id=id).first()
    if not access_level :
        flash(f'No access level with id:{id}', category='error')
        return redirect(url_for('views.access_levels'))
    if request.method == 'POST':
        db.session.delete(access_level)
        db.session.commit()
        flash('Access level deleted', category='success')
        return redirect(url_for('views.access_levels'))
    return render_template("delete_access_level.html", user = current_user, access_level=access_level)


@views.route('/outputs')
@login_required
def outputs():
    devs = Device.query.all()
    return render_template("outputs.html", current_user = current_user, devs = devs)


@views.route('/edit_output/<string:id>', methods=['GET', 'POST'])
@login_required
def edit_output(id):
    output = Output.query.filter_by(id=id).first()
    if not output :
        flash(f'No output with id:{id}', category='error')
        return redirect(url_for('views.outputs'))
    if request.method == 'POST':
        name = request.form.get('Name')
        output.name = name
        db.session.add(output)
        db.session.commit()
        flash('Output information updated', category='success')
        return redirect(url_for('views.outputs'))
    return render_template("edit_output.html", user = current_user, output = output)

ubda/templates/add_person.html
{% extends "base.html" %} {% block title %}new person{% endblock %} 
{% block content %}
<form method="POST">
    <h3 align="center">new person</h3>

    <div class="form-group">
      <label for="firstName">First Name</label>
      <input
        type="text"
        class="form-control"
        id="firstName"
        name="firstName"
        placeholder="Enter first name"
      />
    </div>
    <div class="form-group">
        <label for="lastName">Last Name</label>
        <input
          type="text"
          class="form-control"
          id="lastName"
          name="lastName"
          placeholder="Enter last name"
        />
      </div>
      <div class="form-group">
        <label for="email">email</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
    <div class="form-group">
      <label for="pin">pin</label>
      <input
        type="text"
        class="form-control"
        id="pin"
        name="pin"
        placeholder="Enter pin"
      />
    </div>
    <div class="form-group">
      <label for="card_number">Card number</label>
      <input
        type="number"
        class="form-control"
        id="card_number"
        name="card_number"
        placeholder="Enter card number"
      />
    </div>
    <div class="form-group">
      <label for="accessLevel">Access level</label>
      <select
        class="form-control"
        id="access_level"
        name="access_level"
        placeholder="Access level">
        {% for a in access_levels %}
        <option value={{a.id}}>{{a.name}}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <label for="valid_thru">Valid thru</label>
      <input
        type="date"
        class="form-control"
        id="valid_thru"
        name="valid_thru"
        placeholder="Enter date"
      />
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% endblock %}

ubda/templates/delete_access_level.html
{% extends "base.html" %} {% block title %}Delete{% endblock %} 
{% block nav %}
{% endblock %}
{% block content %}
<h3>delete access level "{{ access_level.name }}" ?<h3>
    <form method="POST">
        <button type="submit" class="btn btn-primary">Yes</button>
    </form>
    <a href = "{{ url_for('views.access_levels') }}">
        <button type="submit" class="btn btn-primary">Cancel</button>
    </a>  
{% endblock %}

ubda/templates/device_log.html
{% extends "base.html" %} {% block title %}Device log{% endblock %} 
{% block content %}

<h3>{{device.name}} ({{device.mac}}) -  log</h3>
<br>
<style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }
  
  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }
  
  tr:nth-child(even) {
    background-color: #dddddd;
  }
  </style>
<table style="width:100%">
  <tr>
    <th>User</th>
    <th>Content</th>
    <th>Date time</th>
  </tr>
  {% for entry in device.log %}
  <tr>
    <td>{{ entry.user }} - {{ user_names[entry.user] }}</td>
    <td>{{ entry.content }}</td>
    <td>{{ entry.date_time }}</td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

ubda/templates/devices.html
{% extends "base.html" %} {% block title %}Devices{% endblock %} 
{% block nav %} 
<a class="nav-item nav-link" id="newDevice" href="/devices">New device</a>
{% endblock %}
{% block content %}

<style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }
  
  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }
  
  tr:nth-child(even) {
    background-color: #dddddd;
  }
  </style>
<table style="width:100%">
  <tr>
    <th>Name</th>
    <th>MAC</th>
    <th>Model</th>
    <th>Last seen</th>
    <th> </th>
    <th> </th>
    <th> </th>
    <th> </th>
    <th> </th>
  </tr>
  {% for dev in devs %}
  <tr>
    <td>{{ dev.name }}</td>
    <td>{{ dev.mac }}</td>
    <td>{{ dev.model }}</td>
    <td>{{ now - dev.last_seen }} seconds ago</td>
    <td><a href="{{ url_for('views.device_log', id = dev.id) }}">Log</a></td>
    <td><a href="{{ url_for('access.url_access', id = dev.mac) }}">Access URL</a></td>
    <td><a href="{{ url_for('access.qr_generator', id = dev.mac) }}">QR</a></td>
    <td><a href="{{ url_for('views.delete_device', id = dev.id) }}">Delete</a></td>
    <td><a href="{{ url_for('views.edit_device', id = dev.id) }}">Edit</a></td>
    <td><a href="{{ url_for('views.reset_device', id = dev.id) }}">Reset</a></td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

ubda/templates/edit_access_level.html
{% extends "base.html" %} {% block title %}Edit Access level{% endblock %} 
{% block content %}
<form method="POST">
    <h3 align="center">Edit Access level</h3>
    <div class="form-group">
        <label for="name">Name</label>
        <input
          type="text"
          class="form-control"
          id="name"
          name="name"
          placeholder="Enter name"
          value = "{{ access_level.name }}"
        />
      </div>
    <div class="form-group">
      <label for="description">Description</label>
      <input
        type="text"
        class="form-control"
        id="description"
        name="description"
        placeholder="Enter description"
        value = "{{ access_level.description }}"
      />
    </div>
    {% for d in devices %}
    <br>
    <label for="{{d.mac}}">{{d.name}} ({{d.mac}}) </label> 
    <input type="checkbox" id="{{d.mac}}" name="{{d.mac}}" value="{{d.mac}}"
    {% if d in access_level.devices %} checked {% endif %}>
    <br>
    {% for o in d.outputs %}
    |<label for="{{o.id}}">{{o.name}} ({{o.n}})</label> 
    <input type="checkbox" id="{{o.id}}" name="{{o.id}}" value="{{o.id}}"
    {% if o in access_level.outputs %} checked {% endif %}> |
    {% endfor %}
    <br><hr>
    {% endfor %}
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

ubda/templates/edit_device.html
{% extends "base.html" %} {% block title %}edit device{% endblock %} 
{% block content %}
<form method="POST">
    <h3 align="center">edit device</h3>

    <div class="form-group">
      <label for="Name">Device name</label>
      <input
        type="text"
        class="form-control"
        id="Name"
        name="Name"
        placeholder="Enter device name"
        value = "{{ device.name }}"/>
      </select>
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% endblock %}

ubda/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block nav %}
<a class="nav-item nav-link" id="change_password" href="/change_password">Change password</a>
{% endblock %}
{% block content%}
<h3>Logged in as {{ user.user_name }}</h3>

{% endblock %}

ubda/templates/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Refresh" content="5; url='{{ url }}'" />
    <title>Message</title>
</head>
<body>
    {% with messages = get_flashed_messages() %} 
    {% if messages %} 
    {% for message in messages %} 
    <h1> 
        {{ message }}
    </h1>
    {% endfor %} {% endif %} {% endwith %}
</body>
</html>

ubda/templates/new_user.html
{% extends "base.html" %} {% block title %}New User{% endblock %} {% block
    content %}
    <form method="POST">
      <h3 align="center">New User</h3>
      <div class="form-group">
        <label for="useraName">User Name</label>
        <input
          type="text"
          class="form-control"
          id="userName"
          name="userName"
          placeholder="Enter user name"
        />
      </div>
      <div class="form-group">
        <label for="firstName">First Name</label>
        <input
          type="text"
          class="form-control"
          id="firstName"
          name="firstName"
          placeholder="Enter first name"
        />
      </div>
      <div class="form-group">
        <label for="password1">Password</label>
        <input
          type="password"
          class="form-control"
          id="password1"
          name="password1"
          placeholder="Enter password"
        />
      </div>
      <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input
          type="password"
          class="form-control"
          id="password2"
          name="password2"
          placeholder="Confirm password"
        />
      </div>
      <div class="form-group">
        <label for="card_number">Card number</label>
        <input
          type="number"
          class="form-control"
          id="card_number"
          name="card_number"
          placeholder="Enter card number"
        />
      </div>
      <div class="form-group">
        <label for="accessLevel">Access level</label>
        <select
          class="form-control"
          id="access_level"
          name="access_level"
          placeholder="Access level">
          {% for a in accessLevels %}
          <option value={{a.id}}>{{a.name}}</option>
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label for="valid_thru">Valid thru</label>
        <input
          type="date"
          class="form-control"
          id="valid_thru"
          name="valid_thru"
          placeholder="Enter date"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endblock %}
    

ubda/templates/outputs.html
{% extends "base.html" %} {% block title %}Outputs{% endblock %} 
{% block content %}

<style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }
  
  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }
  
  tr:nth-child(even) {
    background-color: #dddddd;
  }
  </style>

{% for d in devs %}
<table style="width:100%">
  <th>{{d.name}} ({{d.mac}})</th>
  <tr>
    <th>#</th>
    <th>Name</th>
    <th> </th>
  </tr>
  {% for o in d.outputs %}
  <tr>
    <td>{{ o.n }}</td>
    <td>{{ o.name }}</td>
    <td><a href="{{ url_for('views.edit_output', id = o.id) }}">Edit</a></td>
  </tr>
  {% endfor %} 
</table>
<hr>
{% endfor %}

{% endblock %}

ubda/templates/reset_device.html
{% extends "base.html" %} {% block title %}Reset{% endblock %} 
{% block nav %}
{% endblock %}
{% block content %}
<h3>Reset device "{{ device.name }}({{ device.mac }})" ?<h3>
    <form method="POST">
        <button type="submit" class="btn btn-primary">Yes</button>
    </form>
    <a href = "{{ url_for('views.devices') }}">
        <button type="submit" class="btn btn-primary">Cancel</button>
    </a>  
{% endblock %}

ubda/templates/sign_up.html
{% extends "base.html" %} {% block title %}New User{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">New User</h3>
  <div class="form-group">
    <label for="useraName">User Name</label>
    <input
      type="text"
      class="form-control"
      id="userName"
      name="userName"
      placeholder="Enter user name"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

ubda/templates/user_access_log.html
{% extends "base.html" %} {% block title %}User access log{% endblock %} 
{% block content %}

<h3>{{ user.user_name }} - access log</h3>
<br>
<style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }
  
  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }
  
  tr:nth-child(even) {
    background-color: #dddddd;
  }
  </style>
<table style="width:100%">
  <tr>
    <th>Device</th>
    <th>Content</th>
    <th>Date time</th>
  </tr>
  {% for entry in user.access_log %}
  <tr>
    <td>{{ entry.device }} - "{{ device_names[entry.device] }}"</td>
    <td>{{ entry.content }}</td>
    <td>{{ entry.date_time }}</td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

ubda/templates/users.html
{% extends "base.html" %} {% block title %}Users{% endblock %} 
{% block nav %}
<a class="nav-item nav-link" id="addPerson" href="{{ url_for('user_views.new_user') }}">New user</a>
{% endblock %}
{% block content %}

<style>
  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }
  
  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }
  
  tr:nth-child(even) {
    background-color: #dddddd;
  }
  </style>
<table style="width:100%">
  <tr>
    <th>User name</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Card number</th>
    <th>Access level</th>
    <th>Valid thru</th>
    <th> </th>
    <th> </th>
    <th> </th>
  </tr>
  {% for usr in users %}
  <tr>
    <td>{{ usr.user_name }}</td>
    <td>{{ usr.first_name }}</td>
    <td>{{ usr.last_name }}</td>
    <td>{{ usr.card_number }}</td>
    <td>{{ usr.access_level }} - "{{ access_level_names[usr.access_level] }}"</td>
    <td>{{ usr.valid_thru }}</td>
    <td><a href="{{ url_for('user_views.user_access_log', id = usr.id) }}">Log</a></td>
    <td><a href="{{ url_for('user_views.edit_user', id = usr.id) }}">Edit</a></td>
    <td><a href="{{ url_for('user_views.delete_user', id = usr.id) }}">Delete</a></td>
  </tr>
  {% endfor %}
</table>
{% endblock %}